version: '3.9'
services:
  db:
    container_name: wol-postgres-db
    image: postgres:13.2
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - '5432:5432'
    volumes:
      - ./backend/docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - wol

  backend:
    container_name: wol-server
    build: ./backend
    restart: always
    ports:
      - '9090:9090'
    depends_on:
      - db
    networks:
      - wol
  # frontend:
  #   container_name: wol-frontend

  #   networks:
  #     - wol
networks:
  wol:
    driver: bridge
