version: '3.9'
services:
  db:
    container_name: wol-postgres-db
    image: postgres:13.2
    restart: always
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
      - wol-web-db:/var/lib/postgresql/data
    network_mode: 'host'
  backend:
    container_name: wol-server
    build:
      context: .
      dockerfile: backend.Dockerfile
    restart: always
    depends_on:
      - db
    network_mode: 'host'

  # frontend:
  #   container_name: wol-frontend
# networks:
#   wol:
#     driver: bridge

volumes:
  wol-web-db:
