version: '3.6'
services:
  db:
    image: postgres:13.2
    restart: always
    env_file:
      - ./.env
    ports:
      - '5432:5432'
    volumes:
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
      - ./postgres_data:/var/lib/postgresql/data
